[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "gps"
version = "0.1.1"
description = "GPS library for Lowell Instruments"
dependencies = [
    "pynmea2",
    "pyserial"
]